version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres-db:5432/my_database
    depends_on:
      - postgres-db

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: